"""empty message

Revision ID: 600d97c32af9
Revises: 4b5173ebb3e1
Create Date: 2024-02-21 16:29:57.977294

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '600d97c32af9'
down_revision = '4b5173ebb3e1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Hero_age', table_name='Hero')
    op.drop_index('ix_Hero_id', table_name='Hero')
    op.drop_index('ix_Hero_name', table_name='Hero')
    op.drop_table('Hero')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hero',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Hero_pkey')
    )
    op.create_index('ix_Hero_name', 'Hero', ['name'], unique=False)
    op.create_index('ix_Hero_id', 'Hero', ['id'], unique=False)
    op.create_index('ix_Hero_age', 'Hero', ['age'], unique=False)
    # ### end Alembic commands ###
