"""empty message

Revision ID: f1e1eede41a3
Revises: 600d97c32af9
Create Date: 2024-02-22 08:54:35.455183

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f1e1eede41a3'
down_revision = '600d97c32af9'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Question', 'default_grade')
    op.add_column('Quiz', sa.Column('total_questions_count', sa.Integer(), nullable=True))
    op.drop_column('Quiz', 'total_questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Quiz', sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Quiz', 'total_questions_count')
    op.add_column('Question', sa.Column('default_grade', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
