"""empty message

Revision ID: f1b6a37e31be
Revises: 4c2d3edf4aaa
Create Date: 2024-02-23 00:53:19.305199

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f1b6a37e31be'
down_revision = '4c2d3edf4aaa'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('QuizAnswerSlot', sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('QuizAnswerSlot', 'answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('QuizAnswerSlot', sa.Column('answer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_column('QuizAnswerSlot', 'answer_text')
    # ### end Alembic commands ###
