"""empty message

Revision ID: 4c2d3edf4aaa
Revises: af24c6a654e3
Create Date: 2024-02-23 00:25:50.965543

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '4c2d3edf4aaa'
down_revision = 'af24c6a654e3'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuizAnswerOption',
    sa.Column('quiz_answer_slot_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('option_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_answer_slot_id'], ['QuizAnswerSlot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_QuizAnswerOption_id'), 'QuizAnswerOption', ['id'], unique=False)
    op.drop_column('QuizAnswerSlot', 'answer_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('QuizAnswerSlot', sa.Column('answer_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_QuizAnswerOption_id'), table_name='QuizAnswerOption')
    op.drop_table('QuizAnswerOption')
    # ### end Alembic commands ###
