"""empty message

Revision ID: c86df16f6e13
Revises: 8990cc3e22ed
Create Date: 2024-02-23 07:49:40.585261

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c86df16f6e13'
down_revision = '8990cc3e22ed'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_QuizFeedback_user_id', table_name='QuizFeedback')
    op.drop_column('QuizFeedback', 'feedback_score')
    op.drop_column('QuizFeedback', 'user_id')
    op.drop_index('ix_QuizQuestionFeedback_user_id', table_name='QuizQuestionFeedback')
    op.drop_column('QuizQuestionFeedback', 'feedback_score')
    op.drop_column('QuizQuestionFeedback', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('QuizQuestionFeedback', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('QuizQuestionFeedback', sa.Column('feedback_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_QuizQuestionFeedback_user_id', 'QuizQuestionFeedback', ['user_id'], unique=False)
    op.add_column('QuizFeedback', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('QuizFeedback', sa.Column('feedback_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_QuizFeedback_user_id', 'QuizFeedback', ['user_id'], unique=False)
    # ### end Alembic commands ###
