"""empty message

Revision ID: 4b5173ebb3e1
Revises: abd304978f4e
Create Date: 2024-02-21 14:33:01.267593

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b5173ebb3e1'
down_revision = 'abd304978f4e'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Quiz', sa.Column('has_user_attempted', sa.Boolean(), nullable=False))
    op.add_column('Quiz', sa.Column('total_questions', sa.Integer(), nullable=True))
    op.alter_column('Quiz', 'time_limit',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    op.alter_column('Quiz', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('QuizAttempt', sa.Column('time_start', sa.Interval(), nullable=True))
    op.alter_column('QuizAttempt', 'attempt_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('QuizAttempt', 'time_started')
    op.add_column('UserFile', sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('UserFile', sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('UserFile', sa.Column('bytes', sa.Integer(), nullable=True))
    op.drop_column('UserFile', 'file_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserFile', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('UserFile', 'bytes')
    op.drop_column('UserFile', 'purpose')
    op.drop_column('UserFile', 'file_name')
    op.add_column('QuizAttempt', sa.Column('time_started', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.alter_column('QuizAttempt', 'attempt_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('QuizAttempt', 'time_start')
    op.alter_column('Quiz', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Quiz', 'time_limit',
               existing_type=postgresql.INTERVAL(),
               nullable=False)
    op.drop_column('Quiz', 'total_questions')
    op.drop_column('Quiz', 'has_user_attempted')
    # ### end Alembic commands ###
