version: '3.8'

services:
  fastapi_server:
    container_name: fastapi_server
    build: ./backend
    restart: always
    command: "sh -c 'alembic upgrade head && uvicorn app.main:app --reload --workers 3 --host 0.0.0.0 --port 8000'"
    volumes:
      - ./backend/src:/code
    expose:
      - 8000
    ports:
      - '8000:8000'
    env_file: '.env' # Corrected path here
    environment:
      - ASYNC_DATABASE_URI=${ASYNC_DATABASE_URI}
  #   depends_on:
  #     - database

  # database:
  #   image: bitnami/postgresql:13.3.0
  #   restart: always
  #   container_name: database
  #   env_file: ".env"
  #   user: root
  #   volumes:
  #     - ./db_docker:/bitnami/postgresql
  #     - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
  #   ports:
  #     - 5454:5432 # Remove this on production
  #   expose:
  #     - 5432
  #   environment:
  #     - POSTGRES_USERNAME=${DATABASE_USER}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #     - POSTGRES_DATABASE=${DATABASE_NAME}
  #     - POSTGRES_HOST_AUTH_METHOD= "trust"