version: '3.8'

services:
  aix_fastapi_server:
    container_name: aix_fastapi
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: "sh -c 'alembic upgrade head && gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    volumes:
      - ./backend/app:/code
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file: ".env"
    environment:
      - ASYNC_DATABASE_URI=${ASYNC_DATABASE_URI}
  