"""empty message

Revision ID: 0eaf006791d3
Revises: 
Create Date: 2024-02-19 20:43:25.155534

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '0eaf006791d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hero',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Hero_age'), 'Hero', ['age'], unique=False)
    op.create_index(op.f('ix_Hero_id'), 'Hero', ['id'], unique=False)
    op.create_index(op.f('ix_Hero_name'), 'Hero', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Hero_name'), table_name='Hero')
    op.drop_index(op.f('ix_Hero_id'), table_name='Hero')
    op.drop_index(op.f('ix_Hero_age'), table_name='Hero')
    op.drop_table('Hero')
    # ### end Alembic commands ###
